# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      
    - name: Use Node.js 10.0
      uses: actions/setup-node@v1
      with:
          node-version: 10.0      
      
    - run: npm install -g node-gyp
    - run: npm install -g yarn
      
    - name: Install
    - run: yarn install
      
    - name: Lint
    - run: yarn lint
      
    - name: Test
    - run: yarn test
    
